import type { z } from "zod";
import type {
  ActivitySchema,
  ActivityActionSchema,
  AgentDescriptorSchema,
  AgentIdentitySchema,
  AgentStatusSchema,
  AnswerPayloadSchema,
  ClientFrameSchema,
  ConflictPayloadSchema,
  DecisionOutcomeSchema,
  DecisionPayloadSchema,
  ExecutionRequestPayloadSchema,
  ExecutionResultPayloadSchema,
  HelloFrameSchema,
  MessageKindSchema,
  PresenceEventSchema,
  ProposalPayloadSchema,
  PublishFrameSchema,
  QuestionPayloadSchema,
  ReviewPayloadSchema,
  RoomAgentSchema,
  ServerFrameSchema,
  StatusPayloadSchema,
  StoredMessageSchema,
  TaskPayloadSchema,
  ThoughtPayloadSchema,
  VotePayloadSchema,
  VoteValueSchema,
  WarningCategorySchema,
  WarningPayloadSchema,
  WarningSeveritySchema,
  WelcomeFrameSchema,
} from "./schemas.js";

export type AgentStatus = z.infer<typeof AgentStatusSchema>;
export type AgentIdentity = z.infer<typeof AgentIdentitySchema>;
/** Input shape for joining — optional fields get server-side defaults. */
export type AgentDescriptor = z.input<typeof AgentDescriptorSchema>;
export type Activity = z.infer<typeof ActivitySchema>;
export type ActivityAction = z.infer<typeof ActivityActionSchema>;

export type MessageKind = z.infer<typeof MessageKindSchema>;
export type StoredMessage = z.infer<typeof StoredMessageSchema>;
export type RoomAgent = z.infer<typeof RoomAgentSchema>;

export type StatusPayload = z.infer<typeof StatusPayloadSchema>;
export type ThoughtPayload = z.infer<typeof ThoughtPayloadSchema>;
export type ProposalPayload = z.input<typeof ProposalPayloadSchema>;
export type QuestionPayload = z.infer<typeof QuestionPayloadSchema>;
export type AnswerPayload = z.infer<typeof AnswerPayloadSchema>;
export type WarningPayload = z.infer<typeof WarningPayloadSchema>;
export type WarningSeverity = z.infer<typeof WarningSeveritySchema>;
export type WarningCategory = z.infer<typeof WarningCategorySchema>;
export type ConflictPayload = z.infer<typeof ConflictPayloadSchema>;
export type DecisionPayload = z.infer<typeof DecisionPayloadSchema>;
export type DecisionOutcome = z.infer<typeof DecisionOutcomeSchema>;
export type VotePayload = z.infer<typeof VotePayloadSchema>;
export type VoteValue = z.infer<typeof VoteValueSchema>;
export type TaskPayload = z.infer<typeof TaskPayloadSchema>;
export type ReviewPayload = z.infer<typeof ReviewPayloadSchema>;
export type ExecutionRequestPayload = z.infer<typeof ExecutionRequestPayloadSchema>;
export type ExecutionResultPayload = z.infer<typeof ExecutionResultPayloadSchema>;

/** Client frames use the input shape — the server applies schema defaults on parse. */
export type ClientFrame = z.input<typeof ClientFrameSchema>;
export type ServerFrame = z.infer<typeof ServerFrameSchema>;
export type HelloFrame = z.input<typeof HelloFrameSchema>;
export type PublishFrame = z.infer<typeof PublishFrameSchema>;
export type WelcomeFrame = z.infer<typeof WelcomeFrameSchema>;
export type PresenceEvent = z.infer<typeof PresenceEventSchema>;

/** Sender identity used for messages generated by the server itself. */
export const SYSTEM_SENDER = {
  agentId: "system",
  name: "conclave",
  provider: "conclave",
  role: "system",
} as const;
